---
title: 'Deep Learning Project: malignant vs non-malignant'
author: "By Georgina Anna Wager"
date: "19/01/2021"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Deep learning classification of malignant vs non-malignant melanoma from photographs of the lesion.

This project is part of the assessment for the module C7082 Techniques in Machine Learning and AI, that is ran at Harper Adams University College by Ed Harris for the MSc Course: Data Science for Global Agriculture, Food and Environment. 

#### Github Repository 

Location: https://github.com/georginaanna/C7082-Assesment

Contents:

1. Reproducible code to produce the model
2. A final report in pdf format including an introduction, method, results, discussion and references

Data: 

For the analysis, the data was not collected by myself, and instead was obtained from Kaggle, a website that contains many data sets for keen data science learners to enter competitions and practice predictive modelling and analytics (Shaikh, R, not dated).The location of the data set can be found here: https://www.kaggle.com/c/siim-isic-melanoma-classification/overview 



